### ISSUE TITLE
Implementar CQRS

### ISSUE THREAD

**Issue by dirodriguezm** [alercebroker/lc_classification_step#18]
```[tasklist]
### Tasks
- [ ] https://github.com/alercebroker/lc_classification_step/issues/19
- [ ] https://github.com/alercebroker/lc_classification_step/issues/20
- [ ] https://github.com/alercebroker/lc_classification_step/issues/21
- [ ] https://github.com/alercebroker/kubernetes_pipeline/issues/35
```

![Image](https://user-images.githubusercontent.com/18015991/216419656-b1358df1-ede2-4639-aa9e-b416c55a4118.png)
