### ISSUE TITLE
Incluir modelos de ELASTICC con LC Classifier Step (features)

### ISSUE THREAD

**Issue by dirodriguezm** [alercebroker/lc_classification_step#31]
```[tasklist]
### Tasks
- [ ] https://github.com/alercebroker/lc_classification_step/issues/32
- [ ] https://github.com/alercebroker/lc_classification_step/issues/33
- [ ] https://github.com/alercebroker/lc_classification_step/issues/34
```

Requerimientos:

- Se deben guardar todas las clasificaciones, incluso cuando no hay
- Si no hay clasificación, se debe indicar por qué no se clasificó
- Se debe poder incluir otro modelo en cualquier momento
- Se debe producir un mensaje por cada objeto que entra, con o sin clasificación
- El InputDTO debería tener el campo de features con un valor por defecto con lista vacía
- **OJO**: Este step debe poder ejecutarse en diferentes partes de la pipeline. Si se ejecuta antes que features, la lectura del campo de features debe considerar que no exista

**Comment by pcastelln** [comment]
Schema: https://github.com/LSSTDESC/elasticc/tree/main/alert_schema
